// This file was auto-generated by Fern from our API Definition.

export interface CreateReplacementRulesetResponse {
    /** The unique identifier (UUID) generated for this ruleset. Use this ID in the `ruleset_id` parameter of transcription requests. */
    id: string;
}
