// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Speechall from "../../../index.js";

export declare namespace ReplacementRulesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations for creating and managing custom rulesets to find and replace text within transcriptions.
 */
export class ReplacementRulesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ReplacementRulesClient.Options>;

    constructor(options: ReplacementRulesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Defines a named set of replacement rules (exact match, regex) that can be applied during transcription requests using its `ruleset_id`.
     * Rules within a set are applied sequentially to the transcription text.
     *
     * @param {Speechall.CreateReplacementRulesetRequest} request
     * @param {ReplacementRulesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechall.BadRequestError}
     * @throws {@link Speechall.UnauthorizedError}
     * @throws {@link Speechall.PaymentRequiredError}
     * @throws {@link Speechall.TooManyRequestsError}
     * @throws {@link Speechall.InternalServerError}
     * @throws {@link Speechall.ServiceUnavailableError}
     * @throws {@link Speechall.GatewayTimeoutError}
     *
     * @example
     *     await client.replacementRules.createReplacementRuleset({
     *         name: "Acme Corp Corrections",
     *         rules: [{
     *                 kind: "exact",
     *                 search: "customer X",
     *                 replacement: "[REDACTED CUSTOMER NAME]"
     *             }, {
     *                 kind: "regex",
     *                 pattern: "\\b\\d{4}\\b",
     *                 replacement: "[REDACTED YEAR]"
     *             }]
     *     })
     */
    public createReplacementRuleset(
        request: Speechall.CreateReplacementRulesetRequest,
        requestOptions?: ReplacementRulesClient.RequestOptions,
    ): core.HttpResponsePromise<Speechall.CreateReplacementRulesetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createReplacementRuleset(request, requestOptions));
    }

    private async __createReplacementRuleset(
        request: Speechall.CreateReplacementRulesetRequest,
        requestOptions?: ReplacementRulesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Speechall.CreateReplacementRulesetResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechallEnvironment.Default,
                "replacement-rulesets",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Speechall.CreateReplacementRulesetResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Speechall.BadRequestError(
                        _response.error.body as Speechall.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Speechall.UnauthorizedError(
                        _response.error.body as Speechall.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Speechall.PaymentRequiredError(
                        _response.error.body as Speechall.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Speechall.TooManyRequestsError(
                        _response.error.body as Speechall.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Speechall.InternalServerError(
                        _response.error.body as Speechall.ErrorResponse,
                        _response.rawResponse,
                    );
                case 503:
                    throw new Speechall.ServiceUnavailableError(
                        _response.error.body as Speechall.ErrorResponse,
                        _response.rawResponse,
                    );
                case 504:
                    throw new Speechall.GatewayTimeoutError(
                        _response.error.body as Speechall.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SpeechallError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/replacement-rulesets");
    }
}
