// This file was auto-generated by Fern from our API Definition.

export const TranscribeRequestTimestampGranularity = {
    Word: "word",
    Segment: "segment",
} as const;
export type TranscribeRequestTimestampGranularity =
    (typeof TranscribeRequestTimestampGranularity)[keyof typeof TranscribeRequestTimestampGranularity];
