// This file was auto-generated by Fern from our API Definition.

import type * as Speechall from "../../../index.js";

export type OpenaiCompatibleCreateTranscriptionResponse =
    | Speechall.OpenAiCreateTranscriptionResponseVerboseJson
    | Speechall.OpenAiCreateTranscriptionResponseJson;
