// This file was auto-generated by Fern from our API Definition.

import type * as Speechall from "../index.js";

/**
 * Common configuration options for transcription, applicable to both direct uploads and remote URLs.
 */
export interface BaseTranscriptionConfiguration {
    /** The identifier of the speech-to-text model to use. */
    model: Speechall.TranscriptionModelIdentifier;
    /** The language code (ISO 639-1) of the audio. Defaults to `en`. Use `auto` for automatic detection if supported. */
    language?: Speechall.TranscriptLanguageCode;
    /** The desired format for the transcription output. Defaults to `text`. */
    output_format?: Speechall.TranscriptOutputFormat;
    /** The unique identifier (UUID) of a pre-defined replacement ruleset to apply to the final transcription text. */
    ruleset_id?: string;
    /** Whether to add punctuation. Support varies by model (e.g., Deepgram, AssemblyAI). Defaults to `true`. */
    punctuation?: boolean;
    /** Enable speaker diarization. Defaults to `false`. */
    diarization?: boolean;
    /** Optional text prompt to guide the transcription model. Support varies (e.g., OpenAI). */
    initial_prompt?: string;
    /** Controls output randomness for supported models (e.g., OpenAI). Value between 0 and 1. */
    temperature?: number;
    /** Hint for the number of expected speakers for diarization (e.g., RevAI, Deepgram). */
    speakers_expected?: number;
    /** List of custom words/phrases to improve recognition (e.g., Deepgram, AssemblyAI). */
    custom_vocabulary?: string[];
}
