// This file was auto-generated by Fern from our API Definition.

/**
 * Standard structure for error responses. May include additional properties depending on the error type.
 */
export interface ErrorResponse {
    /** A human-readable message describing the error. */
    message: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
