// This file was auto-generated by Fern from our API Definition.

/**
 * Defines a replacement rule based on finding an exact string match.
 */
export interface ExactRule {
    /** The exact text string to search for within the transcription. */
    search: string;
    /** The text string to replace the found 'search' text with. */
    replacement: string;
    /** If true, the search will match only if the case is identical. If false (default), the search ignores case. */
    caseSensitive?: boolean;
}
