// This file was auto-generated by Fern from our API Definition.

/**
 * Standard JSON response for OpenAI-compatible translation requests when `response_format` is `json`. Contains the translated English text.
 */
export interface OpenAiCreateTranslationResponseJson {
    text: string;
}
