// This file was auto-generated by Fern from our API Definition.

import type * as Speechall from "../index.js";

export interface OpenAiCreateTranslationResponseVerboseJson {
    /** The language of the output translation (always `english`). */
    language: string;
    /** The duration of the input audio. */
    duration: string;
    /** The translated text. */
    text: string;
    /** Segments of the translated text and their corresponding details. */
    segments?: Speechall.OpenAiTranscriptionSegment[];
}
