// This file was auto-generated by Fern from our API Definition.

/** The format of the output, in one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`. */
export const OpenAiAudioResponseFormat = {
    Json: "json",
    Text: "text",
    Srt: "srt",
    VerboseJson: "verbose_json",
    Vtt: "vtt",
} as const;
export type OpenAiAudioResponseFormat = (typeof OpenAiAudioResponseFormat)[keyof typeof OpenAiAudioResponseFormat];
