// This file was auto-generated by Fern from our API Definition.

/**
 * An opaque Speech-to-Text model identifier in `provider.model_name` form. Obtain currently available values from the `/speech-to-text-models` endpoint.
 */
export type OpenTranscriptionModelIdentifier = string;
