// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a transcription response returned by model, based on the provided input.
 */
export interface OpenAiCreateTranscriptionResponseJson {
    /** The transcribed text. */
    text: string;
}
