// This file was auto-generated by Fern from our API Definition.

import type * as Speechall from "../index.js";

/**
 * Represents a verbose json transcription response returned by model, based on the provided input.
 */
export interface OpenAiCreateTranscriptionResponseVerboseJson {
    /** The language of the input audio. */
    language: string;
    /** The duration of the input audio. */
    duration: number;
    /** The transcribed text. */
    text: string;
    /** Extracted words and their corresponding timestamps. */
    words?: Speechall.OpenAiTranscriptionWord[];
    /** Segments of the transcribed text and their corresponding details. */
    segments?: Speechall.OpenAiTranscriptionSegment[];
}
