// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a single word identified during transcription, including its start and end times. Included in `verbose_json` response when `word` granularity is requested.
 */
export interface OpenAiTranscriptionWord {
    /** The text content of the word. */
    word: string;
    /** Start time of the word in seconds. */
    start: number;
    /** End time of the word in seconds. */
    end: number;
}
