// This file was auto-generated by Fern from our API Definition.

/**
 * Defines a replacement rule based on matching a regular expression pattern.
 */
export interface RegexRule {
    /** The regular expression pattern to search for. Uses standard regex syntax (implementation specific, often PCRE-like). Remember to escape special characters if needed (e.g., `\\.` for a literal dot). */
    pattern: string;
    /** The replacement text. Can include backreferences to capture groups from the pattern, like `$1`, `$2`, etc. A literal `$` should be escaped (e.g., `$$`). */
    replacement: string;
    /** An array of flags to modify the regex behavior (e.g., 'i' for case-insensitivity). */
    flags?: RegexRule.Flags.Item[];
}

export namespace RegexRule {
    export type Flags = Flags.Item[];

    export namespace Flags {
        export const Item = {
            I: "i",
            M: "m",
            S: "s",
            X: "x",
            U: "u",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
