// This file was auto-generated by Fern from our API Definition.

/**
 * Defines a replacement rule that uses regex capture groups to apply different replacements to different parts of the matched text.
 */
export interface RegexGroupRule {
    /** The regular expression pattern containing capture groups `(...)`. The entire pattern must match for replacements to occur. */
    pattern: string;
    /** An object where keys are capture group numbers (as strings, e.g., "1", "2") and values are the respective replacement strings for those groups. Groups not listed are kept as matched. The entire match is reconstructed using these replacements. */
    groupReplacements: Record<string, string>;
    /** An array of flags to modify the regex behavior. */
    flags?: RegexGroupRule.Flags.Item[];
}

export namespace RegexGroupRule {
    export type Flags = Flags.Item[];

    export namespace Flags {
        export const Item = {
            I: "i",
            M: "m",
            S: "s",
            X: "x",
            U: "u",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
