// This file was auto-generated by Fern from our API Definition.

import type * as Speechall from "../index.js";

/**
 * Defines a single rule for finding and replacing text in a transcription. Use one of the specific rule types (`ExactRule`, `RegexRule`, `RegexGroupRule`). The `kind` property acts as a discriminator.
 */
export type ReplacementRule =
    | Speechall.ReplacementRule.Exact
    | Speechall.ReplacementRule.Regex
    | Speechall.ReplacementRule.RegexGroup;

export namespace ReplacementRule {
    export interface Exact extends Speechall.ExactRule {
        kind: "exact";
    }

    export interface Regex extends Speechall.RegexRule {
        kind: "regex";
    }

    export interface RegexGroup extends Speechall.RegexGroupRule {
        kind: "regex_group";
    }
}
