// This file was auto-generated by Fern from our API Definition.

import type * as Speechall from "../index.js";

/**
 * Describes an available speech-to-text model, its provider, capabilities, and characteristics.
 */
export interface SpeechToTextModel {
    /** The unique identifier for this model (`provider.model_name`). */
    id: Speechall.TranscriptionModelIdentifier;
    /** A user-friendly name for the model. */
    display_name: string;
    /** The provider of this model. */
    provider: Speechall.TranscriptionProvider;
    /** A brief description of the model, its intended use case, or version notes. */
    description?: string | null;
    /** The cost per second of audio processed in USD. */
    cost_per_second_usd?: number | null;
    /** Indicates whether the model is currently available for use. */
    is_available: boolean;
    /** A list of language codes (preferably BCP 47, e.g., "en-US", "en-GB", "es-ES") supported by this model. May include `auto` if automatic language detection is supported across multiple languages within a single audio file. */
    supported_languages?: string[] | null;
    /** Indicates whether the model generally supports automatic punctuation insertion. */
    punctuation?: boolean | null;
    /** Indicates whether the model generally supports speaker diarization (identifying different speakers). */
    diarization?: boolean | null;
    /** Indicates whether the model can be used for real-time streaming transcription via a WebSocket connection (if offered by Speechall). */
    streamable?: boolean | null;
    /** An approximate measure of processing speed for batch processing. Defined as (audio duration) / (processing time). A higher value means faster processing (e.g., RTF=2 means it processes 1 second of audio in 0.5 seconds). May not be available for all models or streaming scenarios. */
    real_time_factor?: number | null;
    /** The maximum duration of a single audio file (in seconds) that the model can reliably process in one request. May vary by provider or plan. */
    max_duration_seconds?: number | null;
    /** The maximum size of a single audio file (in bytes) that can be uploaded for processing by this model. May vary by provider or plan. */
    max_file_size_bytes?: number | null;
    /** The specific version identifier for the model. */
    version?: string | null;
    /** The date when this specific version of the model was released or last updated. */
    release_date?: string | null;
    /** The primary type or training domain of the model. Helps identify suitability for different audio types. */
    model_type?: SpeechToTextModel.ModelType | null;
    /** A general indication of the model's expected accuracy level relative to other models. Not a guaranteed metric. */
    accuracy_tier?: SpeechToTextModel.AccuracyTier | null;
    /** A list of audio encodings that this model supports or is optimized for (e.g., LINEAR16, FLAC, MP3, Opus). */
    supported_audio_encodings?: string[] | null;
    /** A list of audio sample rates (in Hz) that this model supports or is optimized for. */
    supported_sample_rates?: number[] | null;
    /** Indicates whether the model can provide speaker labels for the transcription. */
    speaker_labels?: boolean | null;
    /** Indicates whether the model can provide timestamps for individual words. */
    word_timestamps?: boolean | null;
    /** Indicates whether the model provides confidence scores for the transcription or individual words. */
    confidence_scores?: boolean | null;
    /** Indicates whether the model supports automatic language detection for input audio. */
    language_detection?: boolean | null;
    /** Indicates if the model can leverage a custom vocabulary or language model adaptation. */
    custom_vocabulary_support?: boolean | null;
    /** Indicates if the model supports filtering or masking of profanity. */
    profanity_filtering?: boolean | null;
    /** Indicates if the model supports noise reduction. */
    noise_reduction?: boolean | null;
    /** Indicates whether the model supports SRT subtitle format output. */
    supports_srt: boolean;
    /** Indicates whether the model supports VTT subtitle format output. */
    supports_vtt: boolean;
    /** Indicates whether the model supports voice activity detection (VAD) to identify speech segments. */
    voice_activity_detection?: boolean | null;
}

export namespace SpeechToTextModel {
    /** The primary type or training domain of the model. Helps identify suitability for different audio types. */
    export const ModelType = {
        General: "general",
        PhoneCall: "phone_call",
        Video: "video",
        CommandAndSearch: "command_and_search",
        Medical: "medical",
        Legal: "legal",
        Voicemail: "voicemail",
        Meeting: "meeting",
    } as const;
    export type ModelType = (typeof ModelType)[keyof typeof ModelType];
    /** A general indication of the model's expected accuracy level relative to other models. Not a guaranteed metric. */
    export const AccuracyTier = {
        Basic: "basic",
        Standard: "standard",
        Enhanced: "enhanced",
        Premium: "premium",
    } as const;
    export type AccuracyTier = (typeof AccuracyTier)[keyof typeof AccuracyTier];
}
