// This file was auto-generated by Fern from our API Definition.

/** The identifier for the underlying Speech-to-Text service provider (e.g., 'openai', 'deepgram'). */
export const TranscriptionProvider = {
    Amazon: "amazon",
    Assemblyai: "assemblyai",
    Azure: "azure",
    Cloudflare: "cloudflare",
    Deepgram: "deepgram",
    Elevenlabs: "elevenlabs",
    Falai: "falai",
    Fireworksai: "fireworksai",
    Gemini: "gemini",
    Gladia: "gladia",
    Google: "google",
    Groq: "groq",
    Ibm: "ibm",
    Mistral: "mistral",
    Openai: "openai",
    Revai: "revai",
    Speechmatics: "speechmatics",
} as const;
export type TranscriptionProvider = (typeof TranscriptionProvider)[keyof typeof TranscriptionProvider];
