// This file was auto-generated by Fern from our API Definition.

import type * as Speechall from "../index.js";

/**
 * Represents the JSON structure returned when a JSON-based `output_format` (`json` or `json_text`) is requested. It can be either a detailed structure or a simple text-only structure.
 */
export type TranscriptionResponse = Speechall.TranscriptionDetailed | Speechall.TranscriptionOnlyText;
