// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a time-coded segment of the transcription, typically corresponding to a phrase, sentence, or speaker turn.
 */
export interface TranscriptionSegment {
    /** The start time of the segment in seconds from the beginning of the audio. */
    start?: number;
    /** The end time of the segment in seconds from the beginning of the audio. */
    end?: number;
    /** The transcribed text content of this segment. */
    text?: string;
    /** An identifier for the speaker of this segment, present if diarization was enabled and successful. */
    speaker?: string;
    /** The model's confidence score for the transcription of this segment, typically between 0 and 1 (if provided by the model). */
    confidence?: number;
}
