// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a word in the transcription, providing time-coded chunks of the transcription.
 */
export interface TranscriptionWord {
    /** The start time of the word in seconds from the beginning of the audio. */
    start: number;
    /** The end time of the word in seconds from the beginning of the audio. */
    end: number;
    /** The transcribed word. */
    word: string;
    /** An identifier for the speaker of this word, present if diarization was enabled and successful. */
    speaker?: string;
    /** The model's confidence score for the transcription of this word, typically between 0 and 1 (if provided by the model). */
    confidence?: number;
}
