// This file was auto-generated by Fern from our API Definition.

/**
 * A simplified JSON response format containing only the transcription ID and the full transcribed text. Returned when `output_format` is `json_text`.
 */
export interface TranscriptionOnlyText {
    /** A unique identifier for the transcription job/request. */
    id: string;
    /** The full transcribed text as a single string. */
    text: string;
}
