// This file was auto-generated by Fern from our API Definition.

/**
 * Specifies the desired format of the transcription output.
 * - `text`: Plain text containing the full transcription.
 * - `json_text`: A simple JSON object containing the transcription ID and the full text (`TranscriptionOnlyText` schema).
 * - `json`: A detailed JSON object including segments, timestamps (based on `timestamp_granularity`), language, and potentially speaker labels and provider metadata (`TranscriptionDetailed` schema).
 * - `srt`: SubRip subtitle format (returned as plain text).
 * - `vtt`: WebVTT subtitle format (returned as plain text).
 */
export const TranscriptOutputFormat = {
    Text: "text",
    JsonText: "json_text",
    Json: "json",
    Srt: "srt",
    Vtt: "vtt",
} as const;
export type TranscriptOutputFormat = (typeof TranscriptOutputFormat)[keyof typeof TranscriptOutputFormat];
