// This file was auto-generated by Fern from our API Definition.

import type * as Speechall from "../index.js";

/**
 * A detailed JSON response format containing the full text, detected language, duration, individual timed segments, and potentially speaker labels and provider-specific metadata. Returned when `output_format` is `json`.
 */
export interface TranscriptionDetailed {
    /** A unique identifier for the transcription job/request. */
    id: string;
    /** The full transcribed text as a single string. */
    text: string;
    /** The detected or specified language of the audio (ISO 639-1 code). */
    language?: string;
    /** An array of transcribed segments, providing time-coded chunks of the transcription. May include speaker labels if diarization was enabled. */
    segments?: Speechall.TranscriptionSegment[];
    /** An array of transcribed words, providing time-coded chunks of the transcription. May include speaker labels if diarization was enabled. */
    words?: Speechall.TranscriptionWord[];
}
