// This file was auto-generated by Fern from our API Definition.

import type * as Speechall from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "Acme Corp Corrections",
 *         rules: [{
 *                 kind: "exact",
 *                 search: "customer X",
 *                 replacement: "[REDACTED CUSTOMER NAME]"
 *             }, {
 *                 kind: "regex",
 *                 pattern: "\\b\\d{4}\\b",
 *                 replacement: "[REDACTED YEAR]"
 *             }]
 *     }
 */
export interface CreateReplacementRulesetRequest {
    /** A user-defined name for this ruleset for easier identification. */
    name: string;
    /** An ordered array of replacement rules. Rules are applied in the order they appear in this list. See the `ReplacementRule` schema for different rule types (exact, regex, regex_group). */
    rules: Speechall.ReplacementRule[];
}
