// This file was auto-generated by Fern from our API Definition.

import type * as Speechall from "../../../../index.js";

/**
 * @example
 *     {
 *         model: "openai.whisper-1",
 *         language: "en",
 *         output_format: "json",
 *         diarization: true,
 *         file_url: "https://example.com/path/to/audio.mp3"
 *     }
 */
export interface RemoteTranscriptionConfiguration extends Speechall.BaseTranscriptionConfiguration {
    /** The publicly accessible URL of the audio file to transcribe. The API server must be able to fetch the audio from this URL. */
    file_url: string;
    /** An array of replacement rules to be applied directly to this transcription request, in order. This allows defining rules inline instead of (or in addition to) using a pre-saved `ruleset_id`. */
    replacement_ruleset?: Speechall.ReplacementRule[];
}
