// This file was auto-generated by Fern from our API Definition.

import { OpenAiCompatibleSpeechToTextClient } from "./api/resources/openAiCompatibleSpeechToText/client/Client.js";
import { ReplacementRulesClient } from "./api/resources/replacementRules/client/Client.js";
import { SpeechToTextClient } from "./api/resources/speechToText/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace SpeechallClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SpeechallClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SpeechallClient.Options>;
    protected _speechToText: SpeechToTextClient | undefined;
    protected _openAiCompatibleSpeechToText: OpenAiCompatibleSpeechToTextClient | undefined;
    protected _replacementRules: ReplacementRulesClient | undefined;

    constructor(options: SpeechallClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get speechToText(): SpeechToTextClient {
        return (this._speechToText ??= new SpeechToTextClient(this._options));
    }

    public get openAiCompatibleSpeechToText(): OpenAiCompatibleSpeechToTextClient {
        return (this._openAiCompatibleSpeechToText ??= new OpenAiCompatibleSpeechToTextClient(this._options));
    }

    public get replacementRules(): ReplacementRulesClient {
        return (this._replacementRules ??= new ReplacementRulesClient(this._options));
    }
}
