// This file was auto-generated by Fern from our API Definition.

export const SpeechallEnvironment = {
    Default: "https://api.speechall.com/v1",
} as const;

export type SpeechallEnvironment = typeof SpeechallEnvironment.Default;
